# IPython log file

get_ipython().run_line_magic('logstart', '')
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn
df = pd.read_csv("iris_flower_dataset.txt")
iris_setosa = df.loc[df["species"]=="Iris-setosa"]
iris_virginica = df.loc[df["species"]=="Iris-virginica"]
iris_versicolor = df.loc[df["species"]=="Iris-versicolor"]
plt.hist(df["sepal_length"])
plt.title("Sepal length")
plt.xlabel("Sepal length")
plt.ylabel("number")
plt.savefig("Sepal length.png")
plt.hist(df["sepal_width"])
plt.xlabel("Sepal width")
plt.ylabel("number")
plt.title("Sepal width")
plt.savefig("Sepal width.png")
plt.hist(df["petal_length"])
plt.hist(df["petal_length"])
plt.title("petal length")
plt.ylabel("number")
plt.xlabel("Petal length")
plt.savefig("Petal length.png")
plt.hist(df["petal_width"])
plt.ylabel("number")
plt.xlabel("Petal width")
plt.title("Petal width")
plt.savefig("Petal width.png")
plt.hist(iris_setosa["sepal_length"], 'r', label = 'Iris setosa')
plt.hist(iris_setosa["sepal_length"],, 'r', label = 'Iris setosa')
plt.hist(iris_setosa["sepal_length"], color = "red" , label = 'Iris setosa')
plt.hist(iris_versicolor["sepal_length"], color = "green" , label = 'Iris versicolor')
plt.hist(iris_virginica["sepal_length"], color = "blue" , label = 'Iris virginica')
plt.legend()
plt.title("Sepal length comparison")
plt.xlabel("sepal length")
plt.ylabel("number")
plt.savefig("Sepal length comparison.png")
plt.hist(iris_setosa["sepal_width"], color = "red" , label = 'Iris setosa')
plt.hist(iris_versicolor["sepal_width"], color = "green" , label = 'Iris versicolor')
plt.hist(iris_virginica["sepal_width"], color = "blue" , label = 'Iris virginica')
plt.ylabel("number")
plt.xlabel("sepal width")
plt.title("Sepal width comparison")
plt.savefig("Sepal width comparison.png")
plt.hist(iris_virginica["petal_width"], color = "blue" , label = 'Iris virginica')
plt.hist(iris_virginica["petal_width"], color = "blue" , label = 'Iris virginica')
plt.hist(iris_setosa["petal_width"], color = "red" , label = 'Iris setosa')
plt.hist(iris_versicolor["petal_width"], color = "green" , label = 'Iris versicolor')
plt.title("petal width")
plt.legend()
plt.xlabel("petal width")
plt.savefig("petal width comparison")
plt.plot(df["sepal_length"), df["sepal_width"])
plt.plot(df["sepal_length"], df["sepal_width"])
plt.plot(df["sepal_length"], df["sepal_width"],'b.')
plt.xlabel("sepal length")
plt.ylabel("sepal width")
plt.title("sepal length vs sepal width")
plt.legend()
plt.title("sepal length vs sepal width (cm)")
plt.ylabel("sepal width (cm)")
plt.xlabel("sepal length (cm)")
plt.saveconfig("sepal length vs sepal width.png")
plt.savefig("sepal length vs sepal width.png")
plt.plot(df["petal_length"], df["petal_width"],'b.')
plt.plot(df["petal_length"], df["petal_width"],'b.')
plt.xlabel("petal length (cm)")
plt.ylabel("petal width (cm)")
plt.title("petal length vs petal width (cm)")
plt.savefig("petal length vs petal width.png")
plt.plot(iris_setosa["sepal_length"],'r.',label = 'Iris Setosa')
plt.plot(iris_versicolor["sepal_length"],'g.', label = 'Iris versicolor')
plt.plot(iris_virginica["sepal_length"],'b.', label = 'Iris virginica')
plt.legend()
plt.title("Sepal length Comparison")
plt.ylabel("Sepal length (cm)")
plt.title("Sepal length Comparison (cm)")
plt.xlabel("Sample")
plt.savefig("Sepal length comparison.png")
plt.plot(iris_setosa["sepal_length"],iris_setosa["sepal_width"]'r.',label = 'Iris Setosa')
plt.plot(iris_setosa["sepal_length"],iris_setosa["sepal_width"],'r.',label = 'Iris Setosa')
plt.plot(iris_virginica["sepal_length"],iris_virginica["sepal_width"],'b.', label = 'Iris virginica')
plt.plot(iris_versicolor["sepal_length"],iris_versicolor["sepal_width"]'g.', label = 'Iris versicolor')
plt.plot(iris_versicolor["sepal_length"],iris_versicolor["sepal_width"],'g.', label = 'Iris versicolor')
plt.legend()
plt.title("Sepal length vs sepal width comparison")
plt.xlabel("Sepal length (cm)")
plt.ylabel("Sepal width (cm)")
plt.title("Sepal length vs sepal width comparison by species type")
plt.savefig("sepal ength vs sepal width by species.png")
plt.plot(iris_setosa["petal_length"], iris_setosa["petal_width"],'r.', label = 'Iris setosa')
plt.plot(iris_virginica["petal_length"],iris_virginica["petal_width"],'b.', label = 'Iris virginica')
plt.plot(iris_versicolor["petal_length"],iris_versicolor["petal_width"],'g.', label = 'Iris versicolor')
plt.legend()
plt.xlabel("petal length (cm)")
plt.ylabel("petal width (cm)")
plt.title("Petal length vs Petal width comparison by species type")
plt.savefig("petal length vs petal width by species")
plt.plot(iris_setosa["sepal_length"], iris_setosa["petal_width"],'r.', label = 'Iris setosa')
plt.plot(iris_setosa["sepal_length"], iris_setosa["petal_length"],'r.', label = 'Iris setosa')
plt.plot(iris_versicolor["sepal_length"],iris_versicolor["petal_length"],'g.', label = 'Iris versicolor')
plt.plot(iris_virginica["sepal_length"],iris_virginica["petal_length"],'b.', label = 'Iris virginica')
plt.title("Sepal length vs Petal length comparison by species type")
plt.xlabel("sepal length (cm)")
plt.ylabel("petal length (cm)")
plt.legend()
plt.savefig("sepal length vs petal length by species.png")
plt.plot(iris_setosa["sepal_width"], iris_setosa["petal_width"],'r.', label = 'Iris setosa')
plt.plot(iris_versicolor["sepal_width"],iris_versicolor["petal_width"],'g.', label = 'Iris versicolor')
plt.plot(iris_virginica["sepal_width"],iris_virginica["petal_width"],'b.', label = 'Iris virginica')
plt.legend()
plt.title("Sepal width vs Petal width comparison by species type")
plt.ylabel("petal width (cm)")
plt.xlabel("sepal width (cm)")
plt.savefig("sepal width vs petal width by species.png")
plt.plot(df["petal_length"])
plt.plot(df["petal_length"], 'b.')
plt.plot(df["sepal_length"], df["petal_length"],'b.')
plt.plot(df["sepal_length"], df["petal_length"],'b.')
plt.title("Sepal length vs petal length (cm)")
plt.xlabel("sepal length (cm)")
plt.ylabel("petal length (cm)")
plt.savefig("Fig 7. Sepal length vs petal length.png")
plt.plot(df["sepal_width"], df["petal_width"],'b.')
plt.title("Sepal width vs petal width (cm)")
plt.ylabel("petal width (cm)")
plt.xlabel("sepal width (cm)")
plt.savefig("Fig 8. Sepal width vs petal width.png")
exit()
